/**
 * Bank checker. Usage: node scripts/problems/check.ts [id ...]
 * Validates every problem JSON in src/problems/bank against the schema, then runs the reference
 * solution AND the brute solution on every sample and hidden test through the real python3 and
 * compares trimmed outputs. Exit 1 on any failure. Also regenerates src/problems/bank/index.ts.
 */
import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { bankProblem, type BankProblem } from "../../src/problems/schema.ts";

const DIR = join(process.cwd(), "src/problems/bank");

function run(code: string, input: string, timeoutMs: number): string {
  return execFileSync("python3", ["-c", code], { input, timeout: timeoutMs, encoding: "utf8", stdio: ["pipe", "pipe", "pipe"] });
}

function norm(s: string): string {
  return s.replace(/\r/g, "").split("\n").map((l) => l.trimEnd()).join("\n").trim();
}

function checkOne(file: string): string[] {
  const errors: string[] = [];
  const raw: unknown = JSON.parse(readFileSync(join(DIR, file), "utf8"));
  const parsed = bankProblem.safeParse(raw);
  if (!parsed.success) return [`${file}: ${parsed.error.issues.map((i) => `${i.path.join(".")}: ${i.message}`).join("; ")}`];
  const p: BankProblem = parsed.data;
  if (`${p.id}.json` !== file) errors.push(`${file}: id ${p.id} does not match the file name`);
  if (!p.statement.includes("Example 1:")) errors.push(`${p.id}: statement has no "Example 1:" block`);
  const cases = [...p.samples.map((c, i) => ({ ...c, name: `sample ${String(i + 1)}` })), ...p.tests.map((c, i) => ({ ...c, name: `test ${String(i + 1)}` }))];
  for (const c of cases) {
    for (const [who, code] of [["solution", p.solution.code], ["brute", p.brute.code]] as const) {
      try {
        const got = norm(run(code, c.input, Math.max(p.timeLimitMs * 3, 15000)));
        if (got !== norm(c.output)) errors.push(`${p.id}: ${who} disagrees on ${c.name}: expected ${JSON.stringify(norm(c.output)).slice(0, 80)} got ${JSON.stringify(got).slice(0, 80)}`);
      } catch (e: unknown) {
        errors.push(`${p.id}: ${who} crashed or timed out on ${c.name}: ${e instanceof Error ? e.message.split("\n")[0] ?? "" : String(e)}`);
      }
    }
  }
  return errors;
}

function writeIndex(ids: string[]): void {
  const lines = ids.map((id, i) => `import p${String(i)} from "./${id}.json";`);
  const body = `${lines.join("\n")}\n\n/** Generated by scripts/problems/check.ts. Do not edit by hand. */\nexport const BANK_RAW: unknown[] = [${ids.map((_, i) => `p${String(i)}`).join(", ")}];\n`;
  writeFileSync(join(DIR, "index.ts"), body);
}

const only = process.argv.slice(2);
const files = readdirSync(DIR).filter((f) => f.endsWith(".json")).sort();
const chosen = only.length === 0 ? files : files.filter((f) => only.includes(f.replace(/\.json$/, "")));
const seen = new Set<string>();
let failures = 0;
for (const f of chosen) {
  const errs = checkOne(f);
  const id = f.replace(/\.json$/, "");
  if (seen.has(id)) errs.push(`${id}: duplicate id`);
  seen.add(id);
  if (errs.length > 0) {
    failures += 1;
    for (const e of errs) console.error(e);
  } else {
    console.log(`ok ${id}`);
  }
}
if (only.length === 0) writeIndex(files.map((f) => f.replace(/\.json$/, "")));
console.log(`${String(chosen.length - failures)}/${String(chosen.length)} problems pass`);
process.exit(failures === 0 ? 0 : 1);
